name: photo_app
description: 'A new Flutter project.'

version: 1.0.0+1

environment:
    sdk: '>=3.2.0-0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    get_it: ^8.0.0
    flutter_bloc: ^8.1.6
    equatable: ^2.0.5
    google_fonts: ^6.2.1
    app_settings: ^5.1.1
    permission_handler: ^11.3.1
    geolocator: ^12.0.0
    connectivity_plus: ^6.1.1
    http: ^1.2.0
    camera: ^0.10.5+9
    native_exif: ^0.6.0
    path_provider: ^2.1.5

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^4.0.0
    lint: ^2.3.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/images/
